### PR TITLE
allow version to intall to be defined as a variable

### PR DESCRIPTION
**Pull request by stevenharradine**

### CODE REVIEW

**Comment by pdufault** [comment]
Looks good to me. :rocket:

**Comment by noqcks** [comment]
side note: maybe we look into haproxy 1.6? http://blog.haproxy.com/2015/10/14/whats-new-in-haproxy-1-6/

**Comment by noqcks** [comment]
other than considering 1.6, I say :cool:

**Comment by pdufault** [comment]
version 1.5 is fine as a sensible default here till we test out v1.6

**Comment by noqcks** [comment]
agreed. just noticing now we're still on 1.5

**Comment by aaronpederson** [comment]
Team approved

**Pull request merged**
