### PR TITLE
Dns watch

### PR DESCRIPTION
**Pull request by stevenharradine**

### CODE REVIEW

**Comment by noqcks** [comment]
:+1: would like to get the travis-ci tests working before we merge anything in

**Comment by noqcks** [comment]
Isn't it possible to do this without a shell script? 

Use the new DNS feature in 1.6? http://blog.haproxy.com/2015/10/14/whats-new-in-haproxy-1-6/

**Comment by stevenharradine** [comment]
ansible-haproxy/requirements.yml
install upstart

**Comment by aaronpederson** [comment]
Reopen when ready

**Pull request closed without merging**
